-- СТ «Дражня» — база данных и безопасность
-- Выполните весь этот файл в Supabase -> SQL Editor.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('news','announcement','document','finance','modernization','gallery','contact')),
  title text not null,
  body text not null default '',
  file_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published boolean not null default true
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.admin_users enable row level security;

-- Посетители видят только опубликованные материалы.
drop policy if exists "public read published posts" on public.posts;
create policy "public read published posts"
on public.posts for select
to anon, authenticated
using (published = true);

-- Администратор может делать всё.
drop policy if exists "admins manage posts" on public.posts;
create policy "admins manage posts"
on public.posts for all
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Пользователь видит только свою запись администратора.
drop policy if exists "admin reads own row" on public.admin_users;
create policy "admin reads own row"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

-- Первый зарегистрированный пользователь автоматически становится администратором.
create or replace function public.make_first_user_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.admin_users) then
    insert into public.admin_users(user_id,email) values (new.id,new.email);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_make_first_admin on auth.users;
create trigger on_auth_user_created_make_first_admin
after insert on auth.users
for each row execute procedure public.make_first_user_admin();

-- Storage: bucket для документов и фотографий.
insert into storage.buckets (id, name, public)
values ('draznya-files', 'draznya-files', true)
on conflict (id) do update set public = true;

drop policy if exists "public read draznya files" on storage.objects;
create policy "public read draznya files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'draznya-files');

drop policy if exists "admins upload draznya files" on storage.objects;
create policy "admins upload draznya files"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'draznya-files'
  and exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

drop policy if exists "admins update draznya files" on storage.objects;
create policy "admins update draznya files"
on storage.objects for update
to authenticated
using (
  bucket_id = 'draznya-files'
  and exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

drop policy if exists "admins delete draznya files" on storage.objects;
create policy "admins delete draznya files"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'draznya-files'
  and exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

-- Права Data API.
grant select on public.posts to anon, authenticated;
grant insert, update, delete, select on public.posts to authenticated;
grant select on public.admin_users to authenticated;
